package com.example.quickbill.util

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिंदी"),
    MARATHI("mr", "मराठी")
}

object AppStrings {
    // English
    private val en = mapOf(
        "app_title" to "QuickBill",
        "home" to "Home",
        "stock" to "Stock",
        "history" to "History",
        "sales" to "Sales",
        "add_new_bill" to "+ Add New Bill",
        "daily_sale" to "Daily Sale",
        "monthly_sale" to "Monthly Sale",
        "low_stock_items" to "Low Stock Items",
        "recent_bills" to "Recent Bills",
        "no_bills_yet" to "No bills recorded yet",
        "view_all_stock" to "View All Stock",
        "customer_name" to "Customer Name",
        "customer_phone" to "Customer Phone No",
        "optional" to "Optional",
        "search_item_placeholder" to "Type Item Number (e.g. 1) or Name...",
        "quantity" to "Quantity",
        "unit" to "Unit",
        "add_item" to "Add Item",
        "bill_no" to "Bill No",
        "total_price" to "Total Price",
        "done_save_bill" to "Done - Create Bill",
        "bill_preview" to "Bill Preview",
        "print" to "Print",
        "download_pdf" to "Share / PDF",
        "new_bill" to "New Bill",
        "available_qty" to "Available",
        "price" to "Price",
        "item_no" to "Item No",
        "item_name" to "Item Name",
        "add_new_item" to "Add New Item",
        "edit_item" to "Edit Item",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "open" to "Open",
        "history_title" to "Customer History",
        "search_history" to "Search by customer name, phone, or bill #",
        "delete_confirm_title" to "Delete this bill?",
        "delete_confirm_msg" to "This will remove the bill and restore sold quantities back to inventory stock.",
        "sales_daily" to "Sales Daily",
        "sales_monthly" to "Monthly Sales",
        "qty_mode" to "Quantity",
        "amount_mode" to "Amount (₹)",
        "today_total" to "Today's Total",
        "month_total" to "This Month's Total",
        "no_sales_data" to "No sales recorded for this period",
        "login_title" to "QuickBill Login",
        "signup_title" to "Create Shop Account",
        "phone_number" to "Phone Number (10 digits)",
        "password" to "Password / PIN",
        "shop_name" to "Shop Name",
        "login_btn" to "Sign In",
        "signup_btn" to "Create Shop & Start",
        "switch_to_signup" to "New shop? Create an account",
        "switch_to_login" to "Already have an account? Sign In",
        "logout" to "Log Out",
        "all_good_stock" to "All items are well stocked"
    )

    // Hindi
    private val hi = mapOf(
        "app_title" to "क्विकबिल",
        "home" to "होम",
        "stock" to "स्टॉक",
        "history" to "इतिहास",
        "sales" to "बिक्री",
        "add_new_bill" to "+ नया बिल बनाएं",
        "daily_sale" to "आज की बिक्री",
        "monthly_sale" to "इस महीने की बिक्री",
        "low_stock_items" to "कम स्टॉक वाले सामान",
        "recent_bills" to "हाल के बिल",
        "no_bills_yet" to "अभी तक कोई बिल नहीं बना",
        "view_all_stock" to "पूरा स्टॉक देखें",
        "customer_name" to "ग्राहक का नाम",
        "customer_phone" to "ग्राहक का मोबाइल नंबर",
        "optional" to "वैकल्पिक",
        "search_item_placeholder" to "सामान का नंबर (उदा. 1) या नाम लिखें...",
        "quantity" to "मात्रा (Qty)",
        "unit" to "इकाई (Unit)",
        "add_item" to "सामान जोड़ें",
        "bill_no" to "बिल नंबर",
        "total_price" to "कुल राशि",
        "done_save_bill" to "बिल पूरा करें (Done)",
        "bill_preview" to "बिल रसीद",
        "print" to "प्रिंट करें",
        "download_pdf" to "पीडीएफ / शेयर करें",
        "new_bill" to "नया बिल",
        "available_qty" to "उपलब्ध",
        "price" to "कीमत",
        "item_no" to "सामान नं.",
        "item_name" to "सामान का नाम",
        "add_new_item" to "नया सामान जोड़ें",
        "edit_item" to "सामान बदलें",
        "save" to "सुरक्षित करें",
        "cancel" to "रद्द करें",
        "delete" to "हटाएं",
        "open" to "खोलें",
        "history_title" to "ग्राहकों के बिल का इतिहास",
        "search_history" to "ग्राहक का नाम, फोन या बिल नं. खोजें",
        "delete_confirm_title" to "क्या यह बिल हटाना चाहते हैं?",
        "delete_confirm_msg" to "बिल हटाने पर सामान का स्टॉक वापस गोदाम में जुड़ जाएगा।",
        "sales_daily" to "दैनिक बिक्री",
        "sales_monthly" to "मासिक बिक्री",
        "qty_mode" to "मात्रा",
        "amount_mode" to "रुपये (₹)",
        "today_total" to "आज का कुल योग",
        "month_total" to "इस महीने का कुल योग",
        "no_sales_data" to "इस अवधि में कोई बिक्री नहीं हुई",
        "login_title" to "क्विकबिल लॉगिन",
        "signup_title" to "दुकान का खाता बनाएं",
        "phone_number" to "मोबाइल नंबर (10 अंक)",
        "password" to "पासवर्ड / पिन",
        "shop_name" to "दुकान का नाम",
        "login_btn" to "लॉगिन करें",
        "signup_btn" to "दुकान शुरू करें",
        "switch_to_signup" to "नई दुकान? नया खाता बनाएं",
        "switch_to_login" to "पहले से खाता है? लॉगिन करें",
        "logout" to "लॉग आउट",
        "all_good_stock" to "सभी सामान पर्याप्त स्टॉक में हैं"
    )

    // Marathi
    private val mr = mapOf(
        "app_title" to "क्विकबिल",
        "home" to "मुख्य",
        "stock" to "स्टॉक",
        "history" to "इतिहास",
        "sales" to "विक्री",
        "add_new_bill" to "+ नवीन बिल बनवा",
        "daily_sale" to "आजची विक्री",
        "monthly_sale" to "या महिन्याची विक्री",
        "low_stock_items" to "कमी स्टॉक असलेले साहित्य",
        "recent_bills" to "नुकतीच बनवलेली बिले",
        "no_bills_yet" to "अजून कोणतीही बिले नाहीत",
        "view_all_stock" to "सर्व स्टॉक पहा",
        "customer_name" to "ग्राहकाचे नाव",
        "customer_phone" to "ग्राहकाचा फोन नंबर",
        "optional" to "ऐच्छिक",
        "search_item_placeholder" to "आयटम नंबर (उदा. 1) किंवा नाव शोधा...",
        "quantity" to "नग / प्रमाण",
        "unit" to "युनिट",
        "add_item" to "आयटम जोडा",
        "bill_no" to "बिल क्र.",
        "total_price" to "एकूण रक्कम",
        "done_save_bill" to "बिल पूर्ण करा (Done)",
        "bill_preview" to "बिल पावती",
        "print" to "प्रिंट करा",
        "download_pdf" to "पीडीएफ / शेअर",
        "new_bill" to "नवीन बिल",
        "available_qty" to "शिल्लक",
        "price" to "दर / किंमत",
        "item_no" to "आयटम क्र.",
        "item_name" to "साहित्याचे नाव",
        "add_new_item" to "नवीन साहित्य जोडा",
        "edit_item" to "बदल करा",
        "save" to "जतन करा",
        "cancel" to "रद्द करा",
        "delete" to "हटवा",
        "open" to "पहा",
        "history_title" to "ग्राहकांच्या बिलांचा इतिहास",
        "search_history" to "नाव, फोन किंवा बिल क्र. ने शोधा",
        "delete_confirm_title" to "हे बिल हटवायचे आहे का?",
        "delete_confirm_msg" to "बिल हटवल्यास विकलेले साहित्य पुन्हा शिल्लक स्टॉकमध्ये जमा होईल.",
        "sales_daily" to "आजची विक्री",
        "sales_monthly" to "महिन्याची विक्री",
        "qty_mode" to "नग / प्रमाण",
        "amount_mode" to "रक्कम (₹)",
        "today_total" to "आजची एकूण विक्री",
        "month_total" to "या महिन्याची एकूण विक्री",
        "no_sales_data" to "या कालावधीत कोणतीही विक्री नोंदवलेली नाही",
        "login_title" to "क्विकबिल लॉगिन",
        "signup_title" to "दुकानाचे खाते उघडा",
        "phone_number" to "मोबाईल नंबर (10 अंक)",
        "password" to "पासवर्ड / पिन",
        "shop_name" to "दुकानाचे नाव",
        "login_btn" to "लॉगिन करा",
        "signup_btn" to "दुकान नोंदवा आणि सुरू करा",
        "switch_to_signup" to "नवीन दुकान? नवीन खाते बनवा",
        "switch_to_login" to "आधीच खाते आहे? लॉगिन करा",
        "logout" to "लॉग आउट",
        "all_good_stock" to "सर्व साहित्य पुरेशा प्रमाणात उपलब्ध आहे"
    )

    fun get(key: String, language: AppLanguage): String {
        val map = when (language) {
            AppLanguage.ENGLISH -> en
            AppLanguage.HINDI -> hi
            AppLanguage.MARATHI -> mr
        }
        return map[key] ?: en[key] ?: key
    }
}
